# Google Cloud Build configuration
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/coiviet:$SHORT_SHA', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/coiviet:$SHORT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'coiviet-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/coiviet:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'  # Singapore (gần VN)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'

images:
  - 'gcr.io/$PROJECT_ID/coiviet:$SHORT_SHA'
