CREATE DATABASE IF NOT EXISTS coivietdb;
CREATE USER IF NOT EXISTS 'coiviet_user'@'%' IDENTIFIED BY 'Coiviet@DB2024!';
GRANT ALL PRIVILEGES ON coivietdb.* TO 'coiviet_user'@'%';
FLUSH PRIVILEGES;
SHOW DATABASES;
